// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeLibrary.Data;

namespace RecipeLibrary.Migrations
{
    [DbContext(typeof(RecipeManagerContext))]
    [Migration("20210317003126_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("RecipeLibrary.Models.IngredientModel", b =>
                {
                    b.Property<int>("IngredientModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(75)");

                    b.Property<int?>("RecipeModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientModelId");

                    b.HasIndex("RecipeModelId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("RecipeLibrary.Models.RecipeModel", b =>
                {
                    b.Property<int>("RecipeModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RecipeModelId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeLibrary.Models.IngredientModel", b =>
                {
                    b.HasOne("RecipeLibrary.Models.RecipeModel", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeModelId");
                });

            modelBuilder.Entity("RecipeLibrary.Models.RecipeModel", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
