// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeLibrary.Data;

namespace RecipeLibrary.Migrations
{
    [DbContext(typeof(RecipeManagerContext))]
    partial class RecipeManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("IngredientModelRecipeModel", b =>
                {
                    b.Property<int>("IngredientsIngredientModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("recipesRecipeModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientsIngredientModelId", "recipesRecipeModelId");

                    b.HasIndex("recipesRecipeModelId");

                    b.ToTable("IngredientModelRecipeModel");
                });

            modelBuilder.Entity("RecipeLibrary.Models.IngredientModel", b =>
                {
                    b.Property<int>("IngredientModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("IngredientModelId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("RecipeLibrary.Models.RecipeModel", b =>
                {
                    b.Property<int>("RecipeModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RecipeModelId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("IngredientModelRecipeModel", b =>
                {
                    b.HasOne("RecipeLibrary.Models.IngredientModel", null)
                        .WithMany()
                        .HasForeignKey("IngredientsIngredientModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeLibrary.Models.RecipeModel", null)
                        .WithMany()
                        .HasForeignKey("recipesRecipeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
