// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeLibrary.Data;

namespace RecipeLibrary.Migrations
{
    [DbContext(typeof(RecipeManagerContext))]
    partial class RecipeManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("RecipeLibrary.Models.IngredientModel", b =>
                {
                    b.Property<int>("IngredientModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecipeModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientModelId");

                    b.HasIndex("RecipeModelId");

                    b.ToTable("ingredients");
                });

            modelBuilder.Entity("RecipeLibrary.Models.RecipeModel", b =>
                {
                    b.Property<int>("RecipeModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeModelId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeLibrary.Models.IngredientModel", b =>
                {
                    b.HasOne("RecipeLibrary.Models.RecipeModel", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeModelId");
                });

            modelBuilder.Entity("RecipeLibrary.Models.RecipeModel", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
